server:
  port: 8000

spring:
  application:
    name: uds-webui
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
zuul:
  routes:
    # 模拟实际环境中的 nginx 反向代理
    gateway:
      path: /sgai-gateway/**
      url: http://localhost:18000
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000

ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000
